apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: techtrends-prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm: 
      valueFiles: 
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/christopherkhan/nd064_course_1.git
    targetRevision: HEAD
  syncPolicy: {}