apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: techtrends-staging
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm: 
      valuesFile: 
      - values-staging.yaml
    path: project/helm
    repoURL: https://github.com/christopherkhan/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}